# This is a config for E2B sandbox template.
# You can use template ID (n50lt33l5pyw2m7lyd3s) or template name (v1-nextjs-test-3) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("v1-nextjs-test-3") # Sync sandbox
# sandbox = await AsyncSandbox.create("v1-nextjs-test-3") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('v1-nextjs-test-3')

team_id = "429f1362-c301-42e7-af33-73a9902430d1"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "v1-nextjs-test-3"
template_id = "n50lt33l5pyw2m7lyd3s"
